### ISSUE TITLE
Team role Sprint 1

### ISSUE THREAD

**Issue by minkkun** [CSDS393-Team-Pandas/panda-games-collection#2]
Team roles, explain what role does, using the matrix in class, everyone has to experience at least one role.

**Comment by adc688** [comment]
The doc includes the RACI matrix: https://docs.google.com/document/d/1MS-UEKPuFnabF5dxfNQj2dyvBscgRm9y2YxKGbbtNR0/edit?usp=sharing

**Comment by minkkun** [comment]
Thanks, Alice :), I will add this matrix to the doc and thus close this issue.
